=== ldtteam/BlockUI/src/main/resources/assets/blockui/gui/block_ui.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
    <xs:element name="window" type="windowType"/>
    <xs:element name="layout" type="layoutType"/>

    <xs:simpleType name="align">
        <xs:restriction base="xs:string">
            <xs:enumeration value="TOP_LEFT"/>
            <xs:enumeration value="TOP_MIDDLE"/>
            <xs:enumeration value="TOP_RIGHT"/>
            <xs:enumeration value="MIDDLE_LEFT"/>
            <xs:enumeration value="MIDDLE"/>
            <xs:enumeration value="MIDDLE_RIGHT"/>
            <xs:enumeration value="BOTTOM_LEFT"/>
            <xs:enumeration value="BOTTOM_MIDDLE"/>
            <xs:enumeration value="BOTTOM_RIGHT"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="sizePair">
        <xs:restriction base="xs:string">
            <xs:pattern value="([-+]?\d+)(%|px)?( +([-+]?\d+)(%|px)?)?"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="fixedSizePair">
        <xs:restriction base="xs:string">
            <xs:pattern value="(-)?\d+( +\d+)?"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="windowType">
        <xs:group ref="paneContainerGroup" minOccurs="0" maxOccurs="unbounded"/>
        <xs:attribute name="inherit" type="xs:string"/>
        <xs:attribute name="size" type="sizePair"/>
        <xs:attribute name="width" type="xs:string"/>
        <xs:attribute name="height" type="xs:string"/>
        <xs:attribute name="lightbox" type="xs:boolean"/>
        <xs:attribute name="pause" type="xs:boolean"/>
        <xs:attribute name="type" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="VANILLA"/>
                    <xs:enumeration value="FULLSCREEN"/>
                    <xs:enumeration value="FULLSCREEN_VANILLA"/>
                    <xs:enumeration value="FIXED"/>
                    <xs:enumeration value="FIXED_VANILLA"/>
                    <xs:enumeration value="OVERSIZED"/>
                    <xs:enumeration value="OVERSIZED_VANILLA"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="layoutType">
        <xs:group ref="paneContainerGroup" minOccurs="0" maxOccurs="unbounded"/>
    </xs:complexType>

    <!-- Pane basic attributes -->
    <xs:complexType name="paneType">
        <xs:attribute name="id" type="xs:string"/>

        <xs:attribute name="align" type="align"/>
        <xs:attribute name="size" type="sizePair"/>
        <xs:attribute name="width" type="xs:string"/>
        <xs:attribute name="height" type="xs:string"/>
        <xs:attribute name="pos" type="sizePair"/>
        <xs:attribute name="x" type="xs:string"/>
        <xs:attribute name="y" type="xs:string"/>

        <xs:attribute name="visible" type="xs:boolean"/>
        <xs:attribute name="enabled" type="xs:boolean"/>
        <xs:attribute name="tooltip" type="xs:string"/>
        <xs:attribute name="onHoverId" type="xs:string"/>

        <xs:attribute name="style" type="xs:string"/>
    </xs:complexType>

    <!-- Abstract text element -->
    <xs:complexType name="textElementType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="textscale" type="xs:string"/>
                <xs:attribute name="textalign" type="align"/>
                <xs:attribute name="color" type="xs:string"/> <!-- overrides all textcolors-->
                <xs:attribute name="textcolor" type="xs:string"/>
                <xs:attribute name="texthovercolor" type="xs:string"/>
                <xs:attribute name="textdisabledcolor" type="xs:string"/>
                <xs:attribute name="shadow" type="xs:boolean"/>
                <xs:attribute name="wrap" type="xs:boolean"/>
                <xs:attribute name="linespace" type="xs:integer"/>
                <xs:attribute name="text" type="xs:string"/>
                <xs:attribute name="label" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- View basic attributes and contents -->
    <xs:complexType name="viewType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:group ref="paneContainerGroup" minOccurs="0" maxOccurs="unbounded"/>
                <xs:attribute name="padding" type="xs:integer"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- Scroll view basic attributes and contents -->
    <xs:complexType name="scrollViewType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="childspacing" type="xs:integer"/>
                <xs:attribute name="scrollbarOffset" type="fixedSizePair"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- Master group for all panes that can be used -->
    <xs:group name="paneContainerGroup">
        <xs:choice>
            <xs:element name="layout" type="layoutElementType"/>
            <xs:element name="view" type="viewType"/>
            <xs:element name="zoomdragview" type="zoomDragType"/>
            <xs:element name="group" type="groupType"/>
            <xs:element name="scrollgroup" type="scrollViewType"/>
            <xs:element name="list" type="listType"/>
            <xs:element name="button" type="buttonType"/>
            <xs:element name="toggle" type="toggleType"/>
            <xs:element name="text" type="textType"/>
            <xs:element name="input" type="inputType"/>
            <xs:element name="image" type="imageType"/>
            <xs:element name="imagerepeat" type="imageRepeatType"/>
            <xs:element name="gradient" type="gradientType"/>
            <xs:element name="box" type="boxType"/>
            <xs:element name="itemicon" type="itemIconType"/>
            <xs:element name="entityicon" type="entityIconType"/>
            <xs:element name="switch" type="switchType"/>
            <xs:element name="dropdown" type="dropdownType"/>
            <xs:element name="checkbox" type="checkboxType"/>
        </xs:choice>
    </xs:group>

    <!-- <layout> -->
    <xs:complexType name="layoutElementType">
        <xs:attribute name="source" use="required"/>
    </xs:complexType>

    <!-- <group> -->
    <xs:complexType name="groupType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="spacing" type="xs:integer"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <switch> -->
    <xs:complexType name="switchType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="default" type="xs:string"/>
                <xs:attribute name="endless" type="xs:boolean"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <box> -->
    <xs:complexType name="boxType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="color" type="xs:string"/>
                <xs:attribute name="linewidth" type="xs:decimal"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <list> -->
    <xs:complexType name="listType">
        <xs:complexContent>
            <xs:extension base="scrollViewType">
                <xs:group ref="paneContainerGroup" minOccurs="1" maxOccurs="1"/>

                <xs:attribute name="emptytext" type="xs:string"/>
                <xs:attribute name="emptyscale" type="xs:string"/>
                <xs:attribute name="emptycolor" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <button> -->
    <xs:complexType name="buttonType">
        <xs:complexContent>
            <xs:extension base="textElementType">
                <xs:attribute name="source" type="xs:string"/>
                <xs:attribute name="highlight" type="xs:string"/>
                <xs:attribute name="disabled" type="xs:string"/>
                <xs:attribute name="textoffset" type="fixedSizePair"/>
                <xs:attribute name="textbox" type="fixedSizePair"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <text> -->
    <xs:complexType name="textType">
        <xs:complexContent>
            <xs:extension base="textElementType"></xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <itemicon> -->
    <xs:complexType name="itemIconType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="item" type="xs:string"/>
                <xs:attribute name="nbt" type="xs:string"/>
                <xs:attribute name="properties" type="xs:string"/>
                <xs:attribute name="renderItemDecorations" type="xs:boolean" default="true"/>
                <xs:attribute name="alwaysAddBlockStateTooltip" type="xs:boolean" default="false"/>
            </xs:extension>
        </xs:complexContent>
        <!-- TODO:
            <xs:assert test="(@nbt and not(@properties)) or (not(@nbt) and @properties)"/>
        -->
    </xs:complexType>

    <!-- <entityicon> -->
    <xs:complexType name="entityIconType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="entity" type="xs:string"/>
                <xs:attribute name="count" type="xs:integer"/>
                <xs:attribute name="yaw" type="xs:float"/>
                <xs:attribute name="pitch" type="xs:float"/>
                <xs:attribute name="head" type="xs:float"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <toggle> -->
    <xs:complexType name="toggleType">
        <xs:complexContent>
            <xs:extension base="buttonType">
                <xs:attribute name="options" type="xs:string" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <image> -->
    <xs:complexType name="imageType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="source" type="xs:string"/>
                <xs:attribute name="imageoffset" type="fixedSizePair"/>
                <xs:attribute name="imagesize" type="fixedSizePair"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="imageRepeatType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="source" type="xs:string"/>
                <xs:attribute name="textureoffset" type="fixedSizePair"/>
                <xs:attribute name="texturesize" type="fixedSizePair"/>
                <xs:attribute name="repeatoffset" type="fixedSizePair"/>
                <xs:attribute name="repeatsize" type="fixedSizePair"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <gradient> -->
    <xs:complexType name="gradientType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="gradientstart" type="xs:string"/>
                <xs:attribute name="gradientend" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <input> -->
    <xs:complexType name="inputType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:attribute name="textContent" type="xs:string"/>
                <xs:attribute name="maxlength" type="xs:integer"/>
                <xs:attribute name="color" type="xs:string"/>
                <xs:attribute name="colordisabled" type="xs:string"/>
                <xs:attribute name="shadow" type="xs:boolean"/>
                <xs:attribute name="tab" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <dropdown> -->
    <xs:complexType name="dropdownType">
        <xs:complexContent>
            <xs:extension base="paneType">
                <xs:group ref="paneContainerGroup" minOccurs="1" maxOccurs="1"/>
                <xs:attribute name="padding" type="xs:integer"/>
                <xs:attribute name="maxContentHeight" type="xs:integer"/>
                <xs:attribute name="dropDownSize" type="fixedSizePair"/>
                <xs:attribute name="source" type="xs:string"/>
                <xs:attribute name="textcolor" type="xs:string"/>
                <xs:attribute name="scrollbarOffset" type="fixedSizePair"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <zoom> -->
    <xs:complexType name="zoomDragType">
        <xs:complexContent>
            <xs:extension base="viewType">
                <xs:attribute name="dragfactor" type="xs:double"/>
                <xs:attribute name="dragenabled" type="xs:boolean"/>
                <xs:attribute name="zoomfactor" type="xs:double"/>
                <xs:attribute name="zoomenabled" type="xs:boolean"/>
                <xs:attribute name="minscale" type="xs:double"/>
                <xs:attribute name="maxscale" type="xs:double"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- <checkbox> -->
    <xs:complexType name="checkboxType">
        <xs:complexContent>
            <xs:extension base="buttonType">
                <xs:attribute name="checkmark" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

</xs:schema>

=== ldtteam/BlockUI/src/main/resources/assets/blockui/gui/test.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="block_ui.xsd" size="1600 900" type="FIXED_VANILLA" pause="true" lightbox="true">
    <button id="bt" label="vanilla" size="100 100" pos="0 0" textscale="5"/>
    <button id="bti" label="textured" size="100 100" pos="100 0" textscale="5" textoffset="18 18" textbox="64 64" source="blockui:button" cursor="blockui:textures/gui/test_cursor.png"/>
    <text id="txt" size="600 250" pos="0 100" textcolor="yellow" tooltip="test tooltip" textscale="3.5" textalign="BOTTOM_RIGHT" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eros elit, tempus quis imperdiet iaculis, dignissim ac velit. Donec sed molestie sem. Fusce lacinia est nec nibh lobortis aliquet. Aliquam lorem est, vehicula sodales lorem ac, mollis faucibus felis. Fusce facilisis suscipit mi. Fusce luctus erat et magna rutrum ullamcorper. Phasellus placerat, nulla in mattis mattis, purus nunc elementum nisl, ac tristique risus neque in dolor. Nunc a sagittis ligula. Sed ut placerat elit, a ultricies purus. Nullam vel gravida ante.\nProin mattis lobortis tellus sit amet semper. Integer ut viverra nunc. Donec dictum tincidunt laoreet. Pellentesque ultrices dapibus ex, ut iaculis odio. Ut suscipit, nibh eu condimentum gravida, sapien neque blandit ipsum, eget laoreet ipsum erat id felis. Fusce tempor dui sit amet bibendum tristique. Curabitur sodales, leo sit amet blandit rhoncus, arcu est gravida nibh, vitae fringilla sapien nunc vel nisl. Praesent a tristique tortor. Nullam facilisis nisi at augue condimentum ornare. Aliquam vitae sem ipsum. Quisque varius ut dolor at sagittis. Suspendisse vehicula mattis massa vitae hendrerit. Nunc blandit suscipit enim."/>
    <itemicon item="minecraft:birch_log" size="16 16" pos="0 570"/>
    <itemicon item="minecraft:bundle" nbt='{"minecraft:bundle_contents": [{count: 1, id: "minecraft:redstone"}, {count: 1, components: {"minecraft:potion_contents": {potion: "minecraft:long_turtle_master"}}, id: "minecraft:tipped_arrow"}, {count: 1, components: {"minecraft:potion_contents": {potion: "minecraft:turtle_master"}}, id: "minecraft:tipped_arrow"}, {count: 1, components: {"minecraft:potion_contents": {potion: "minecraft:strong_healing"}}, id: "minecraft:tipped_arrow"}, {count: 1, components: {"minecraft:potion_contents": {potion: "minecraft:strong_strength"}}, id: "minecraft:tipped_arrow"}, {count: 1, components: {"minecraft:potion_contents": {potion: "minecraft:long_weakness"}}, id: "minecraft:tipped_arrow"}, {count: 1, components: {"minecraft:fireworks": {flight_duration: 3b}}, id: "minecraft:firework_rocket"}, {count: 1, id: "minecraft:spectral_arrow"}, {count: 1, id: "minecraft:snowball"}, {count: 2, id: "minecraft:birch_stairs"}, {count: 1, id: "minecraft:birch_wood"}, {count: 1, id: "minecraft:birch_door"}, {count: 16, id: "minecraft:stripped_jungle_wood"}, {count: 8, id: "minecraft:egg"}]}' size="16 16" pos="16 570"/>
    <itemicon item="minecraft:netherite_upgrade_smithing_template" size="16 16" pos="32 570"/>
    <itemicon item="minecraft:lime_shulker_box" size="16 16" pos="48 570" nbt='{"minecraft:container": [{item: {count: 1, id: "minecraft:birch_stairs"}, slot: 0}]}'/>
    <input id="txtin" size="400 100" pos="0 600"/>
    <image id="vanilla_uv_test" pos="0 750" size="728 20" imageoffset="185 548" imagesize="182 5" source="minecraft:textures/atlas/gui.png"/>
    <image id="missing" pos="120 800" size="100 100" source="blockui:veryuglymissingtexture"/>
    <image id="missing_out_of_jar" pos="240 800" size="100 100" source="blockui:veryuglymissingtexture"/>
    <image id="working_out_of_jar" pos="360 800" size="100 100" source="blockui:veryuglymissingtexture"/>
    <image id="anim_test" pos="0 800" size="100 100" source="blockui:spritesheet_leaves"/>
    <button id="unicodeTest" cursor="blockui:missingcursortexture" size="50 50" label="↥" pos="600 270"  textscale="3.5"/>
    <zoomdragview id="zdv" pos="800 0" size="800 900">
        <scrollgroup pos="0 0" size="109 900" childspacing="10">
            <button size="100 100" label="0" textscale="10"/>
            <button size="100 100" label="1" textscale="10"/>
            <button size="100 100" label="2" textscale="10"/>
            <button size="100 100" label="3" textscale="10"/>
            <button size="100 100" label="4" textscale="10"/>
            <button size="100 100" label="5" textscale="10"/>
            <button size="100 100" label="6" textscale="10"/>
            <button size="100 100" label="7" textscale="10"/>
            <button size="100 100" label="8" textscale="10"/>
            <button size="100 100" label="9" textscale="10"/>
            <dropdown size="100 20">
                <image size="100 100" source="blockui:button"/>
            </dropdown>
            <button size="100 100" label="10" textscale="10"/>
            <button size="100 100" label="11" textscale="10"/>
            <button size="100 100" label="12" textscale="10"/>
            <button size="100 100" label="13" textscale="10"/>
            <button size="100 100" label="14" textscale="10"/>
            <button size="100 100" label="15" textscale="10"/>
            <button size="100 100" label="16" textscale="10"/>
            <button size="100 100" label="17" textscale="10"/>
        </scrollgroup>
        <dropdown size="100 20" pos="150 0">
            <image size="100 100" source="blockui:button"/>
        </dropdown>
        <itemicon id="ii" item="minecraft:barrier" onHoverId="ii2" size="16 16" pos="0 400"/>
        <itemicon id="ii2" item="minecraft:diamond_pickaxe" pos="0 416" size="16 16"/>
        <gradient pos="100 500" size="100 100" gradientstart="rgb(0,0,0)" gradientend="rgb(255,255,255)"/>
        <itemicon item="minecraft:oak_fence" nbt="{block_state:{south:'true',waterlogged:'true'}}" size="64 64" pos="300 50"/>
        <itemicon item="domum_ornamentum:plain" nbt="{block_state:{facing:'up'}, block_entity_data:{id:'domum_ornamentum:materially_retexturable',textureData:{'minecraft:block/oak_planks':'minecraft:polished_basalt','minecraft:block/dark_oak_planks':'minecraft:red_stained_glass'}}}" size="64 64" pos="370 50"/>
        <itemicon item="minecraft:oak_stairs" nbt="{block_state:{waterlogged:'true',facing:'south'}}" size="64 64" pos="440 50"/>
        <itemicon item="minecraft:oak_stairs" nbt="{block_state:{facing:'east'}}" size="64 64" pos="510 50"/>
        <itemicon item="minecraft:oak_stairs" size="64 64" pos="580 50"/>
        <itemicon item="minecraft:clock" properties="{_item:{time:0.5}}" size="32 32" pos="650 50"/>
        <itemicon item="minecraft:clock" size="32 32" pos="700 50"/>
        <image id="player_skin" pos="300 300" size="128 128" source="blockui:veryuglymissingtexture"/>
        <image id="player_cape" pos="428 300" size="128 64" source="blockui:veryuglymissingtexture"/>
        <image id="player_elytra" pos="556 300" size="128 128" source="blockui:veryuglymissingtexture"/>
        <image id="repeat_blit" pos="300 500" size="70 70" source="blockui:repeat_blit"/>
        <image id="repeat_blit_stretch" pos="400 500" size="70 70" source="blockui:repeat_blit_stretch"/>
    </zoomdragview>
</window>

=== ldtteam/BlockUI/src/main/resources/assets/blockui/gui/test4.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="block_ui.xsd" size="640 480" pause="true" lightbox="true">
    <list id="list1" size="160 240">
        <text size="152 20"/>
    </list>
    <list id="list2" size="160 240" pos="160 0">
        <text size="152 20"/>
    </list>
    <list id="list3" size="160 240" pos="320 0">
        <view size="152 20">
            <text size="100 20"/>
            <checkbox pos="120 3"
                size="14 15"
                id="checkbox"
                source="blockui:button_mini"
                disabled="blockui:button_mini_disabled"
                checkmark="blockui:overlay_mini_check"/>
        </view>
    </list>
    <list id="list4" size="160 200" pos="480 0" emptytext="This list is empty" emptyscale="0.8" emptycolor="white">
        <text size="152 20"/>
    </list>
    <button id="list4add" pos="480 200" size="160 20" label="Add item"/>
    <button id="list4remove" pos="480 220" size="160 20" label="Remove item"/>
    <list id="list5" size="160 200" pos="0 240" emptytext="This list is empty" emptyscale="0.8" emptycolor="white">
        <text size="152 20"/>
    </list>
    <button id="list5update" pos="0 440" size="160 20" label="Update list"/>
</window>

=== ldtteam/BlockUI/src/main/resources/assets/blockui/gui/test2.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="block_ui.xsd" size="320 240" lightbox="true">
    <itemicon item="minecraft:diamond_pickaxe" pos="0 192" size="64 64"/>
    <itemicon item="minecraft:diamond_pickaxe" pos="0 128" size="64 64"/>
    <itemicon item="minecraft:diamond_pickaxe" pos="0 64" size="64 64"/>
    <itemicon item="minecraft:diamond_pickaxe" pos="0 0" size="64 64"/>
    <itemicon item="minecraft:diamond_pickaxe" pos="64 0" size="64 64"/>
    <itemicon item="minecraft:diamond_pickaxe" pos="128 0" size="64 64"/>
    <itemicon item="minecraft:diamond_pickaxe" pos="192 0" size="64 64"/>
    <itemicon item="minecraft:diamond_pickaxe" pos="256 0" size="64 64"/>
    <itemicon item="minecraft:diamond_pickaxe" pos="256 128" size="64 64"/>
    <itemicon item="minecraft:diamond_pickaxe" pos="256 192" size="64 64"/>
    <itemicon item="minecraft:brush" pos="128 128" size="64 64"/>
    <itemicon item="minecraft:bundle" nbt='{"minecraft:bundle_contents": [{count: 1, id: "minecraft:redstone"}, {count: 1, components: {"minecraft:potion_contents": {potion: "minecraft:long_turtle_master"}}, id: "minecraft:tipped_arrow"}, {count: 1, components: {"minecraft:potion_contents": {potion: "minecraft:turtle_master"}}, id: "minecraft:tipped_arrow"}, {count: 1, components: {"minecraft:potion_contents": {potion: "minecraft:strong_healing"}}, id: "minecraft:tipped_arrow"}, {count: 1, components: {"minecraft:potion_contents": {potion: "minecraft:strong_strength"}}, id: "minecraft:tipped_arrow"}, {count: 1, components: {"minecraft:potion_contents": {potion: "minecraft:long_weakness"}}, id: "minecraft:tipped_arrow"}, {count: 1, components: {"minecraft:fireworks": {flight_duration: 3b}}, id: "minecraft:firework_rocket"}, {count: 1, id: "minecraft:spectral_arrow"}, {count: 1, id: "minecraft:snowball"}, {count: 2, id: "minecraft:birch_stairs"}, {count: 1, id: "minecraft:birch_wood"}, {count: 1, id: "minecraft:birch_door"}, {count: 16, id: "minecraft:stripped_jungle_wood"}, {count: 8, id: "minecraft:egg"}]}' size="16 16" pos="192 192"/>
    <text pos="64 64" size="300 20" textscale="1.4" text="1.4 textscale normal gui test"/>
</window>

=== ldtteam/BlockUI/src/main/resources/assets/blockui/gui/test5.xml
<window xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="block_ui.xsd" size="1600 900" type="FIXED" pause="true" lightbox="true">

    <!-- =====================================================
         ROW 1: Section labels
         ===================================================== -->
    <text pos="10 10"  size="400 40" textscale="2.0" color="yellow" text="1. Both slots filled"/>
    <text pos="440 10" size="400 40" textscale="2.0" color="yellow" text="2. Default slot only"/>
    <text pos="870 10" size="400 40" textscale="2.0" color="yellow" text="3. Fallback (no content)"/>

    <!-- =====================================================
         CASE 1: card.xml with both named header + default body filled
         ===================================================== -->
    <view pos="10 55">
        <layout source="blockui:gui/layout/card.xml">
            <text slot="header" text="Hello Header" size="396 40" pos="4 4" color="white" textscale="1.6"/>
            <text text="Body content here" size="396 132" pos="4 4" color="lime" textscale="1.6"/>
        </layout>
    </view>

    <!-- =====================================================
         CASE 2: card.xml with only default slot filled, header uses fallback
         ===================================================== -->
    <view pos="440 55">
        <layout source="blockui:gui/layout/card.xml">
            <text text="Only body filled" size="396 132" pos="4 4" color="aqua" textscale="1.6"/>
        </layout>
    </view>

    <!-- =====================================================
         CASE 3: card.xml with no slot content at all — both use fallbacks
         ===================================================== -->
    <view pos="870 55">
        <layout source="blockui:gui/layout/card.xml"/>
    </view>

    <!-- =====================================================
         ROW 2: Section label
         ===================================================== -->
    <text pos="10 270" size="600 40" textscale="2.0" color="yellow" text="4. labeled_row layout (named slots)"/>

    <!-- =====================================================
         CASE 4: labeled_row with named label + content slots, using pos on layout tag
         ===================================================== -->
    <view pos="10 315">
        <layout source="blockui:gui/layout/labeled_row.xml" pos="0 0">
            <text slot="label" text="Name:" size="180 32" pos="0 4" textscale="1.8" color="white"/>
            <text slot="content" text="Steve" size="310 32" pos="0 4" textscale="1.8" color="lime"/>
        </layout>
        <layout source="blockui:gui/layout/labeled_row.xml" pos="0 50">
            <text slot="label" text="Level:" size="180 32" pos="0 4" textscale="1.8" color="white"/>
            <text slot="content" text="42" size="310 32" pos="0 4" textscale="1.8" color="aqua"/>
        </layout>
        <!-- label fallback used, only content provided -->
        <layout source="blockui:gui/layout/labeled_row.xml" pos="0 100">
            <text slot="content" text="(label is fallback)" size="310 32" pos="0 4" textscale="1.8" color="orange"/>
        </layout>
        <!-- no slots filled: label fallback shown, content slot is empty (no fallback) -->
        <layout source="blockui:gui/layout/labeled_row.xml" pos="0 150"/>
    </view>

</window>
